[phases.install]
cmds = ["pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "gunicorn lang_platform.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"
