# Generated by Django 5.0.3 on 2025-09-15 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trophy",
            fields=[
                (
                    "id",
                    models.SlugField(max_length=60, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=120)),
                ("category", models.CharField(max_length=40)),
                ("trigger_type", models.CharField(max_length=20)),
                ("metric", models.CharField(max_length=80)),
                ("comparator", models.CharField(max_length=10)),
                ("threshold", models.JSONField()),
                ("window", models.CharField(max_length=30)),
                ("subject_scope", models.CharField(default="any", max_length=20)),
                ("repeatable", models.BooleanField(default=False)),
                ("cooldown", models.CharField(default="none", max_length=10)),
                ("points", models.IntegerField(default=0)),
                ("icon", models.CharField(default="trophy", max_length=30)),
                ("rarity", models.CharField(default="common", max_length=12)),
                ("description", models.TextField(default="")),
                ("constraints", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="TrophyUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "trophy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="achievements.trophy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trophy_unlocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "trophy", "earned_at"],
                        name="achievement_user_id_606bce_idx",
                    )
                ],
                "unique_together": {("user", "trophy", "earned_at")},
            },
        ),
    ]
