# Generated by Django 5.0.3 on 2025-09-06 15:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0034_assignmentprogress_completed"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("exposure", "Exposure"),
                            ("tapping", "Tapping"),
                            ("mcq", "Multiple Choice"),
                            ("typing", "Typing"),
                            ("listening", "Listening"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("time_taken_ms", models.IntegerField(blank=True, null=True)),
                ("hints_used", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.student",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.word"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentWordProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("learning", "Learning"),
                            ("reviewing", "Reviewing"),
                            ("mastered", "Mastered"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("box_index", models.SmallIntegerField(default=0)),
                (
                    "strength",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("times_correct", models.IntegerField(default=0)),
                ("times_incorrect", models.IntegerField(default=0)),
                ("streak", models.SmallIntegerField(default=0)),
                (
                    "ease",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2.5"), max_digits=4
                    ),
                ),
                (
                    "last_activity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exposure", "Exposure"),
                            ("tapping", "Tapping"),
                            ("mcq", "Multiple Choice"),
                            ("typing", "Typing"),
                            ("listening", "Listening"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "suggested_next_activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exposure", "Exposure"),
                            ("tapping", "Tapping"),
                            ("mcq", "Multiple Choice"),
                            ("typing", "Typing"),
                            ("listening", "Listening"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("is_difficult", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.student",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.word"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["student", "next_due_at"],
                        name="srs_student_student_e7094d_idx",
                    ),
                    models.Index(
                        fields=["student", "is_difficult", "next_due_at"],
                        name="srs_student_student_beb015_idx",
                    ),
                ],
                "unique_together": {("student", "word")},
            },
        ),
    ]
