# Generated by Django 5.0.3 on 2025-09-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("srs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentwordprogress",
            name="lesson_errors",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentwordprogress",
            name="lesson_path_index",
            field=models.SmallIntegerField(default=0),
        ),
    ]
