# Generated by Django 5.0.3 on 2025-11-10 04:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-ts",),
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_no",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "heat",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("lane_or_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("DNS", "Did Not Start"),
                            ("DQ", "Disqualified"),
                        ],
                        default="CONFIRMED",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ("event", "round_no", "heat", "lane_or_order"),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("grade_min", models.CharField(max_length=10)),
                ("grade_max", models.CharField(max_length=10)),
                (
                    "gender_limit",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Mixed/Open")],
                        max_length=1,
                    ),
                ),
                ("measure_unit", models.CharField(max_length=8)),
                ("capacity", models.PositiveIntegerField(default=8)),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("rounds_total", models.PositiveIntegerField(default=1)),
                ("knockout_qualifiers", models.CharField(blank=True, max_length=120)),
                ("schedule_dt", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("schedule_dt", "name"),
            },
        ),
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("max_events_per_student", models.PositiveIntegerField(default=3)),
                ("notes", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-date", "name"),
            },
        ),
        migrations.CreateModel(
            name="SportType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=80)),
                (
                    "archetype",
                    models.CharField(
                        choices=[
                            ("TRACK_TIME", "Track (timed)"),
                            ("FIELD_DISTANCE", "Field (distance)"),
                            ("FIELD_COUNT", "Field (count)"),
                            ("RANK_ONLY", "Rank only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_unit",
                    models.CharField(
                        choices=[
                            ("sec", "Seconds"),
                            ("m", "Metres"),
                            ("cm", "Centimetres"),
                            ("count", "Count"),
                        ],
                        max_length=8,
                    ),
                ),
                ("default_capacity", models.PositiveIntegerField(default=8)),
                ("default_attempts", models.PositiveIntegerField(default=1)),
                ("supports_heats", models.BooleanField(default=True)),
                ("supports_finals", models.BooleanField(default=True)),
                ("requires_time_for_first_place", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("label",),
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("dob", models.DateField()),
                ("grade", models.CharField(max_length=10)),
                ("house", models.CharField(max_length=64)),
                ("gender", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_no",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "time_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "distance_m",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                ("valid", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="sportsday.entry",
                    ),
                ),
            ],
            options={
                "ordering": ("entry", "attempt_no"),
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="sportsday.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="sportsday.meet",
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "best_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("tiebreak", models.JSONField(blank=True, default=dict)),
                ("finalized", models.BooleanField(default=False)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="sportsday.entry",
                    ),
                ),
            ],
            options={
                "ordering": ("rank", "entry__event__name"),
            },
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points_csv",
                    models.CharField(default="10,8,6,5,4,3,2,1", max_length=120),
                ),
                (
                    "participation_point",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "tie_method",
                    models.CharField(
                        choices=[("SHARE", "Share points"), ("SKIP", "Skip points")],
                        default="SHARE",
                        max_length=8,
                    ),
                ),
                (
                    "meet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_rules",
                        to="sportsday.meet",
                    ),
                ),
            ],
            options={
                "ordering": ("meet", "id"),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="sport_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="sportsday.sporttype",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="sportsday.student",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="assigned_teachers",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="sportsday.teacher"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("event", "student", "round_no"), name="unique_entry_per_round"
            ),
        ),
    ]
