# Generated by Django 5.0.3 on 2025-11-08 13:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TIME", "Time"),
                            ("DISTANCE", "Distance"),
                            ("COUNT", "Count"),
                            ("RANK", "Rank"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gender_limit",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("X", "Open")],
                        default="X",
                        max_length=16,
                    ),
                ),
                ("grade_min", models.CharField(max_length=10)),
                ("grade_max", models.CharField(max_length=10)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(128),
                        ],
                    ),
                ),
                (
                    "rounds",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                ("measure_unit", models.CharField(default="sec", max_length=16)),
                ("marshal_pin_hash", models.CharField(blank=True, max_length=128)),
                ("schedule_block", models.CharField(blank=True, max_length=32)),
                ("location", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("schedule_block", "name"),
            },
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("color", models.CharField(blank=True, max_length=16)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Meet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("date", models.DateField()),
                ("access_code_hash", models.CharField(blank=True, max_length=128)),
                ("max_events_per_student", models.PositiveIntegerField(default=3)),
                ("is_locked", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("-date", "name"),
            },
        ),
        migrations.CreateModel(
            name="SportsdayAccessConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_hash", models.CharField(blank=True, max_length=128)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "cookie_name",
                    models.CharField(default="sportsday_access", max_length=32),
                ),
                (
                    "cookie_ttl_hours",
                    models.PositiveIntegerField(
                        default=12,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(72),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Sports Day access configuration",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(blank=True, max_length=64)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("dob", models.DateField()),
                ("grade", models.CharField(max_length=10)),
                ("house", models.CharField(max_length=32)),
                ("gender", models.CharField(max_length=16)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("last_name", "first_name"),
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                ("action", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-ts",),
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heat", models.PositiveIntegerField(default=1)),
                ("lane_or_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("DNS", "Did Not Start"),
                            ("DQ", "Disqualified"),
                        ],
                        default="CONFIRMED",
                        max_length=16,
                    ),
                ),
                ("override_limits", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="sportsday.event",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="sportsday.student",
                    ),
                ),
            ],
            options={
                "ordering": ("event", "heat", "lane_or_order"),
                "unique_together": {("event", "student")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="meet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="sportsday.meet",
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "round_no",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "time_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "distance_m",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("count", models.IntegerField(blank=True, null=True)),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "wind",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=120)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="sportsday.entry",
                    ),
                ),
            ],
            options={
                "ordering": ("round_no", "rank", "entry__lane_or_order"),
            },
        ),
        migrations.CreateModel(
            name="ScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("EVENT", "Event"),
                            ("PARTICIPATION", "Participation"),
                        ],
                        default="EVENT",
                        max_length=16,
                    ),
                ),
                (
                    "points_csv",
                    models.CharField(default="10,8,6,5,4,3,2,1", max_length=120),
                ),
                ("per_house", models.BooleanField(default=True)),
                (
                    "tie_method",
                    models.CharField(
                        choices=[("SHARE", "Share"), ("SKIP", "Skip")],
                        default="SHARE",
                        max_length=16,
                    ),
                ),
                (
                    "meet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_rules",
                        to="sportsday.meet",
                    ),
                ),
            ],
            options={
                "ordering": ("scope", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scope", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                (
                    "meet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_snapshots",
                        to="sportsday.meet",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["meet", "scope", "created_at"],
                        name="sportsday_l_meet_id_991371_idx",
                    )
                ],
            },
        ),
    ]
