# Generated by Django 5.0.3 on 2025-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsday", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meet",
            name="allowed_grades",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
