# Generated by Django 5.0.3 on 2025-12-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sportsday", "0003_fix_relay_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": (
                    models.OrderBy(models.F("schedule_dt"), nulls_last=True),
                    "pk",
                )
            },
        ),
        migrations.AlterField(
            model_name="sporttype",
            name="default_unit",
            field=models.CharField(
                choices=[
                    ("sec", "Seconds"),
                    ("m", "Metres"),
                    ("cm", "Centimetres"),
                    ("ft_in", "Feet & inches"),
                    ("count", "Count"),
                ],
                max_length=8,
            ),
        ),
    ]
