"""URL configuration for the sportsday app."""
from django.urls import path

from . import views

app_name = "sportsday"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("meets/", views.meet_list, name="meet-list"),
    path("meets/sync-events/", views.meet_sync_event_dates, name="meet-sync-events"),
    path("meets/new/", views.meet_create, name="meet-create"),
    path("meets/<slug:slug>/edit/", views.meet_update, name="meet-update"),
    path("meets/<slug:slug>/", views.meet_detail, name="meet-detail"),
    path("meets/<slug:slug>/schedule/", views.meet_schedule_fragment, name="meet-schedule-fragment"),
    path("meets/<slug:slug>/people/", views.meet_people_fragment, name="meet-people-fragment"),
    path("meets/<slug:slug>/lock/", views.meet_toggle_lock, name="meet-toggle-lock"),
    path("meets/<slug:slug>/delete/", views.meet_delete, name="meet-delete"),
    path("meets/<slug:slug>/events/generate/", views.events_generate, name="events-generate"),
    path("meets/<slug:slug>/events/import/", views.events_import, name="events-import"),
    path(
        "meets/<slug:slug>/events/backup/download/",
        views.events_backup_download,
        name="events-backup-download",
    ),
    path(
        "meets/<slug:slug>/events/backup/upload/",
        views.events_backup_upload,
        name="events-backup-upload",
    ),
    path("meets/<slug:slug>/entries/bulk/", views.entries_bulk, name="entries-bulk"),
    path("students/upload/", views.students_upload, name="students-upload"),
    path("students/", views.student_list, name="students"),
    path("students/<int:student_id>/edit/", views.student_edit, name="student-edit"),
    path("students/<int:student_id>/delete/", views.student_delete, name="student-delete"),
    path("students/table/", views.students_table_fragment, name="students-table-fragment"),
    path("teachers/upload/", views.teachers_upload, name="teachers-upload"),
    path("teachers/", views.teacher_list, name="teachers"),
    path("teachers/table/", views.teachers_table_fragment, name="teachers-table-fragment"),
    path("sports/", views.sport_type_admin, name="sport-types"),
    path("events/", views.event_list, name="events"),
    path("events/quick/", views.quick_assignments, name="quick-assignments"),
    path(
        "events/quick/student-search/",
        views.quick_assignment_student_search,
        name="quick-assignments-student-search",
    ),
    path(
        "events/quick/events/",
        views.quick_assignment_event_search,
        name="quick-assignments-events",
    ),
    path(
        "events/quick/undo/",
        views.quick_assignments_undo,
        name="quick-assignments-undo",
    ),
    path("events/new/", views.event_create, name="event-create"),
    path("events/table/", views.events_table_fragment, name="events-table-fragment"),
    path("events/reassign/", views.event_reassign, name="event-reassign"),
    path("events/<int:pk>/edit/", views.event_update, name="event-update"),
    path("events/<int:pk>/delete/", views.event_delete, name="event-delete"),
    path("events/<int:event_id>/manage/", views.manage_event, name="manage-event"),
    path(
        "events/<int:pk>/participants/",
        views.event_participants,
        name="event-participants",
    ),
    path("events/<int:pk>/", views.event_detail, name="event-detail"),
    path("events/<int:pk>/lock/", views.event_toggle_lock, name="event-toggle-lock"),
    path("events/<int:pk>/start-list/", views.event_start_list_fragment, name="event-start-list-fragment"),
    path("events/<int:pk>/start-list/add/", views.event_start_list_add, name="event-start-list-add"),
    path(
        "events/<int:pk>/start-list/remove/<int:entry_id>/",
        views.event_start_list_remove,
        name="event-start-list-remove",
    ),
    path("events/<int:pk>/start-list/reorder/", views.event_start_list_reorder, name="event-start-list-reorder"),
    path(
        "events/<int:pk>/start-list/autobalance/",
        views.event_start_list_autobalance,
        name="event-start-list-autobalance",
    ),
    path(
        "events/<int:pk>/start-list/autoseed/",
        views.event_start_list_autoseed,
        name="event-start-list-autoseed",
    ),
    path("events/<int:pk>/results/", views.event_results_fragment, name="event-results-fragment"),
    path("events/<int:pk>/printables/", views.event_printables_fragment, name="event-printables-fragment"),
    path("events/<int:pk>/printables/start-list/", views.event_start_list_printable, name="event-start-list-printable"),
    path("events/<int:pk>/printables/marshal-cards/", views.event_marshal_cards_printable, name="event-marshal-cards-printable"),
    path("events/<int:pk>/printables/medal-labels/", views.event_medal_labels_printable, name="event-medal-labels-printable"),
    path("events/<int:pk>/qr/", views.event_results_qr, name="event-results-qr"),
    path("leaderboards/", views.leaderboards, name="leaderboards"),
    path("leaderboards/panel/", views.leaderboards_panel_fragment, name="leaderboards-panel-fragment"),
    path("exports/events/overview/", views.export_events_overview, name="export-events-overview"),
    path(
        "exports/events/teacher-allocations/",
        views.export_teacher_allocations,
        name="export-teacher-allocations",
    ),
    path("exports/events/schedule/", views.export_event_schedule, name="export-event-schedule"),
    path("exports/students.csv", views.export_students_csv, name="export-students-csv"),
    path("exports/teachers.csv", views.export_teachers_csv, name="export-teachers-csv"),
    path("exports/startlists.csv", views.export_startlists_csv, name="export-startlists-csv"),
    path("exports/results.csv", views.export_results_csv, name="export-results-csv"),
    path("exports/results/ticker/", views.export_results_ticker, name="export-results-ticker"),
    path("exports/leaderboard.csv", views.export_leaderboard_csv, name="export-leaderboard-csv"),
    path("meets/template/<str:kind>/", views.meet_download_template, name="meet-template"),
]
