# Generated by ChatGPT

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("learning", "0041_clubsession_clubattendance_studentcalendarentry_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveGameSession",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("pin", models.CharField(db_index=True, max_length=6, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("LOBBY", "Lobby"), ("RUNNING", "Running"), ("ENDED", "Ended")],
                        default="LOBBY",
                        max_length=8,
                    ),
                ),
                ("total_questions", models.PositiveIntegerField()),
                ("question_time_sec", models.PositiveIntegerField(default=20)),
                (
                    "scoring_mode",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("FAST", "Fast"), ("STREAKY", "Streaky")],
                        default="STANDARD",
                        max_length=12,
                    ),
                ),
                ("current_question_idx", models.IntegerField(default=0)),
                ("current_question_started_at", models.DateTimeField(blank=True, null=True)),
                ("current_question_deadline", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clazz",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="live_game_sessions",
                        to="learning.class",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        limit_choices_to={"is_teacher": True},
                        on_delete=models.deletion.CASCADE,
                        related_name="hosted_live_games",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vocab_lists",
                    models.ManyToManyField(
                        related_name="live_game_sessions",
                        to="learning.vocabularylist",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="LiveGameParticipant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_name", models.CharField(max_length=64)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_connected", models.BooleanField(default=True)),
                ("score", models.IntegerField(default=0)),
                ("streak", models.IntegerField(default=0)),
                ("total_latency_ms", models.IntegerField(default=0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="participants",
                        to="live.livegamesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="live_game_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-score", "total_latency_ms", "joined_at"),
            },
        ),
        migrations.CreateModel(
            name="LiveGameQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.PositiveIntegerField()),
                ("payload", models.JSONField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="questions",
                        to="live.livegamesession",
                    ),
                ),
            ],
            options={
                "ordering": ("index",),
            },
        ),
        migrations.CreateModel(
            name="LiveGameAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_correct", models.BooleanField()),
                ("latency_ms", models.IntegerField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="answers",
                        to="live.livegameparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="answers",
                        to="live.livegamequestion",
                    ),
                ),
            ],
            options={
                "ordering": ("submitted_at",),
            },
        ),
        migrations.AlterUniqueTogether(
            name="livegameparticipant",
            unique_together={("session", "user"), ("session", "display_name")},
        ),
        migrations.AlterUniqueTogether(
            name="livegamequestion",
            unique_together={("session", "index")},
        ),
        migrations.AlterUniqueTogether(
            name="livegameanswer",
            unique_together={("participant", "question")},
        ),
    ]
