# Generated by Django 4.2.18 on 2025-03-05 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_alter_user_ai_credits'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livegame',
            name='class_instance',
            field=models.ForeignKey(default='3208fe35-ce64-4343-9f7a-4e3d6b46514f', on_delete=django.db.models.deletion.CASCADE, to='learning.class'),
            preserve_default=False,
        ),
    ]
