# Generated by Django 4.2.18 on 2025-03-05 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_alter_user_ai_credits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_livegame_class_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='game_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livegame',
            name='class_instance',
            field=models.ForeignKey(default='3208fe35-ce64-4343-9f7a-4e3d6b46514f', on_delete=django.db.models.deletion.CASCADE, to='learning.class'),
        ),
    ]
