# Generated by Django 5.0.3 on 2025-03-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameteam_members_alter_livegame_class_instance'),
        ('learning', '0025_alter_user_ai_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameteam',
            name='members',
        ),
        migrations.AlterField(
            model_name='livegame',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.class'),
        ),
    ]
