# Generated by Django 5.1.4 on 2025-01-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_student_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularylist',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='vocabulary_lists', to='learning.class'),
        ),
    ]
