# Generated by Django 5.1.4 on 2025-01-14 16:19

import learning.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_school_word_user_is_lead_teacher_class_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='key',
            field=models.CharField(default=learning.models.generate_school_key, max_length=10, unique=True),
        ),
    ]
