# Generated by Django 5.1.4 on 2025-01-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_alter_school_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='weekly_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
