# Generated by Django 4.2.18 on 2025-01-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_student_monthly_points_student_total_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='vocabulary_lists',
            field=models.ManyToManyField(related_name='linked_classes', to='learning.vocabularylist'),
        ),
        migrations.AlterField(
            model_name='vocabularylist',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='linked_vocab_lists', to='learning.class'),
        ),
    ]
