# Generated by Django 4.2.18 on 2025-01-18 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_class_vocabulary_lists_alter_vocabularylist_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='vocabulary_lists',
            field=models.ManyToManyField(blank=True, related_name='linked_classes', to='learning.vocabularylist'),
        ),
        migrations.AlterField(
            model_name='vocabularyword',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='learning.vocabularylist'),
        ),
    ]
