# Generated by Django 4.2.18 on 2025-01-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_assignment_assignmentprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='points_per_destroy_wall',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points_per_fill_gap',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points_per_flashcard',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points_per_matchup',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points_per_unscramble',
            field=models.IntegerField(default=1),
        ),
    ]
