# Generated by Django 4.2.18 on 2025-01-30 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_assignment_points_per_destroy_wall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentprogress',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
