# Generated by Django 4.2.18 on 2025-01-30 08:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_alter_assignmentprogress_time_spent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='trophies/')),
                ('points_required', models.IntegerField(blank=True, null=True)),
                ('streak_required', models.IntegerField(blank=True, null=True)),
                ('assignment_count_required', models.IntegerField(blank=True, null=True)),
                ('game_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='learning.student')),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='learning.trophy')),
            ],
            options={
                'unique_together': {('student', 'trophy')},
            },
        ),
    ]
