# Generated by Django 4.2.18 on 2025-02-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_assignment_include_listening_dictation_and_more'),
    ]

    # Country field was already added in a previous migration.
    operations = []