# Generated by Django 4.2.18 on 2025-02-05 08:39

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_assignment_include_listening_dictation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(blank=True, null=True),
        ),
    ]