# Generated by Django 4.2.18 on 2025-02-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_user_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
