# Generated by Django 4.2.18 on 2025-02-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0021_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_credits',
            field=models.IntegerField(default=5),
        ),
    ]
