# Generated by Django 4.2.18 on 2025-02-24 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0022_user_ai_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingLabText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('exam_board', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=10)),
                ('word_count', models.IntegerField()),
                ('selected_vocab', models.TextField()),
                ('generated_text_source', models.TextField()),
                ('generated_text_target', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
