# Generated by Django 4.2.18 on 2025-02-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_readinglabtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinglabtext',
            name='selected_vocab',
        ),
        migrations.AddField(
            model_name='readinglabtext',
            name='selected_words',
            field=models.ManyToManyField(related_name='included_in_reading_lab', to='learning.vocabularyword'),
        ),
        migrations.AddField(
            model_name='readinglabtext',
            name='vocabulary_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.vocabularylist'),
        ),
        migrations.AlterField(
            model_name='readinglabtext',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='readinglabtext',
            name='word_count',
            field=models.PositiveIntegerField(),
        ),
    ]
