# Generated by Django 4.2.18 on 2025-03-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0024_remove_readinglabtext_selected_vocab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ai_credits',
            field=models.IntegerField(default=1),
        ),
    ]
