# Generated by Django 5.0.3 on 2025-03-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_alter_user_ai_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.student')),
                ('vocabulary_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.vocabularyword')),
            ],
        ),
    ]
