# Generated by Django 5.0.3 on 2025-03-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_assignmentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='mode',
            field=models.CharField(choices=[('flashcards', 'Flashcards'), ('matchup', 'Matchup'), ('fill_gap', 'Gap Fill'), ('destroy_wall', 'Destroy the Wall'), ('unscramble', 'Unscramble'), ('listening_dictation', 'Listening Dictation'), ('listening_translation', 'Listening Translation')], default='matchup', max_length=30),
            preserve_default=False,
        ),
    ]
