# Generated by Django 5.0.3 on 2025-04-04 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_assignmentattempt_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarLadder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prompt', models.TextField()),
                ('language', models.CharField(choices=[('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Italian', 'Italian')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_ladders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LadderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('ladder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learning.grammarladder')),
            ],
        ),
    ]
