# Generated by Django 5.0.3 on 2025-08-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0028_grammarladder_ladderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="review_count",
            field=models.IntegerField(default=0),
        ),
    ]
