# Generated by Django 5.0.3 on 2025-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0028_grammarladder_ladderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progress",
            old_name="interval",
            new_name="review_interval",
        ),
        migrations.AddField(
            model_name="progress",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progress",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
