# Generated by Django 5.0.3 on 2025-08-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0029_progress_last_seen_progress_review_count"),
        ("learning", "0029_rename_interval_progress_review_interval_and_more"),
    ]

    operations = []
