# Generated by Django 5.0.3 on 2025-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0030_merge_20250829_0936"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progress",
            old_name="review_interval",
            new_name="interval",
        ),
        migrations.AlterField(
            model_name="progress",
            name="review_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
