# Generated by Django 5.0.3 on 2025-08-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0031_rename_review_interval_progress_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="last_seen",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
