# Generated by Django 5.0.3 on 2025-09-04 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0032_alter_progress_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="monthly_points_last_reset",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="student",
            name="weekly_points_last_reset",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
