# Generated by Django 5.0.3 on 2025-09-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0033_student_monthly_points_last_reset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentprogress",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
