# Generated by Django 5.0.3 on 2025-09-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0035_vocabularylist_created_at_vocabularylist_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularyword",
            name="image_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="image_attribution",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="image_license",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="image_source",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="image_thumb_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="word_fact_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="word_fact_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="word_fact_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vocabularyword",
            name="word_fact_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
