# Generated by Django 5.0.3 on 2025-09-17 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0036_vocabularyword_image_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
