# Generated by Django 5.0.3 on 2025-09-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0037_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mini_game_1_best_streak",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
