# Generated by Django 5.0.3 on 2025-09-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0038_student_mini_game_1_best_streak"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
