# Generated by Django 5.0.3 on 2025-11-07 07:24

import learning.models
from django.db import migrations, models


def copy_school_codes(apps, schema_editor):
    School = apps.get_model("learning", "School")
    used_codes = set()

    for school in School.objects.all():
        raw_code = getattr(school, "key", "") or ""
        candidate = (raw_code[:6] or "").upper()

        if not candidate:
            candidate = (school.school_code or "").upper()

        while (
            not candidate
            or len(candidate) != 6
            or School.objects.filter(school_code=candidate).exclude(pk=school.pk).exists()
            or candidate in used_codes
        ):
            candidate = learning.models.generate_school_code()

        school.school_code = candidate
        school.save(update_fields=["school_code"])
        used_codes.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0041_clubsession_clubattendance_studentcalendarentry_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_lead_teacher",
            new_name="is_school_lead",
        ),
        migrations.AddField(
            model_name="school",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="school_logos/"),
        ),
        migrations.AddField(
            model_name="school",
            name="school_code",
            field=models.CharField(
                default=learning.models.generate_school_code, max_length=6, unique=True
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(copy_school_codes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="school",
            name="key",
        ),
        migrations.AddField(
            model_name="vocabularylist",
            name="shared_with_school",
            field=models.BooleanField(default=False),
        ),
    ]
